services:
  carbonnowapi:
    build:
      context: .
      dockerfile: CarbonNowAPI/Dockerfile
    image: carbonnowapi
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  db:
    container_name: mydb
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
