// <auto-generated />
using System;
using CarbonNowAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CarbonNowAPI.Migrations
{
    [DbContext(typeof(DatabaseConnection))]
    [Migration("20250617003859_TabelaTransporte")]
    partial class TabelaTransporte
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("SEQ_ID_ELETRICIDADE");

            modelBuilder.HasSequence<int>("SEQ_ID_TRANSPORTE");

            modelBuilder.HasSequence<int>("SEQ_ID_USUARIO");

            modelBuilder.Entity("CarbonNowAPI.Model.Eletricidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValueSql("SEQ_ID_ELETRICIDADE.NEXTVAL");

                    b.Property<decimal>("CarbonoKg")
                        .HasColumnType("NUMBER(18,2)");

                    b.Property<DateTime>("DataEstimacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasDefaultValueSql("TRUNC(SYSDATE)");

                    b.Property<string>("UnidadeEletricidade")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR2(3)")
                        .HasDefaultValueSql("'KWH'");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("ValorEletricidade")
                        .HasColumnType("NUMBER(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Eletricidade", (string)null);
                });

            modelBuilder.Entity("CarbonNowAPI.Model.Transporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValueSql("SEQ_ID_TRANSPORTE.NEXTVAL");

                    b.Property<decimal>("CarbonoKg")
                        .HasColumnType("NUMBER(18,2)");

                    b.Property<DateTime>("DataEstimacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasDefaultValueSql("TRUNC(SYSDATE)");

                    b.Property<string>("MetodoTransporte")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("NVARCHAR2(5)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("ValorDistanciaKm")
                        .HasColumnType("NUMBER(18,2)");

                    b.Property<decimal>("ValorPesoKg")
                        .HasColumnType("NUMBER(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Transporte", (string)null);
                });

            modelBuilder.Entity("CarbonNowAPI.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValueSql("SEQ_ID_USUARIO.NEXTVAL");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<string>("Regra")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("CarbonNowAPI.Model.Eletricidade", b =>
                {
                    b.HasOne("CarbonNowAPI.Model.Usuario", "Usuario")
                        .WithMany("Eletricidade")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CarbonNowAPI.Model.Transporte", b =>
                {
                    b.HasOne("CarbonNowAPI.Model.Usuario", "Usuario")
                        .WithMany("Transporte")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CarbonNowAPI.Model.Usuario", b =>
                {
                    b.Navigation("Eletricidade");

                    b.Navigation("Transporte");
                });
#pragma warning restore 612, 618
        }
    }
}
